config/routes.rb
Rails.application.routes.draw do
 # devise setup
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # home page
  root to: 'site#home'
  get 'site/home'

  resources :activities
  resources :activity_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :set_activity_type, only: [:show, :edit, :update, :destroy]

  # GET /activity_types
  # GET /activity_types.json
  def index
    @activity_types = ActivityType.all
  end

  # GET /activity_types/1
  # GET /activity_types/1.json
  def show
  end

  # GET /activity_types/new
  def new
    @activity_type = ActivityType.new
  end

  # GET /activity_types/1/edit
  def edit
  end

  # POST /activity_types
  # POST /activity_types.json
  def create
    @activity_type = ActivityType.new(activity_type_params)

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully created.' }
        format.json { render :show, status: :created, location: @activity_type }
      else
        format.html { render :new }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_types/1
  # PATCH/PUT /activity_types/1.json
  def update
    respond_to do |format|
      if @activity_type.update(activity_type_params)
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_type }
      else
        format.html { render :edit }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_types/1
  # DELETE /activity_types/1.json
  def destroy
    @activity_type.destroy
    respond_to do |format|
      format.html { redirect_to activity_types_url, notice: 'Activity type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_type
      @activity_type = ActivityType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_type_params
      params.fetch(:activity_type, {})
    end
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
    activity_types_array = ActivityType.all.map
end

app/views/activity_types/_form.html.erb
<%= form_with(model: activity_type, local: true) do |form| %>
  <% if activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
        <% activity_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activity_types/edit.html.erb
<h1>Editing Activity Type</h1>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Show', @activity_type %> |
<%= link_to 'Back', activity_types_path %>

app/views/activity_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activity Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_types.each do |activity_type| %>
      <tr>
        <td><%= link_to 'Show', activity_type %></td>
        <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
        <td><%= link_to 'Destroy', activity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity Type', new_activity_type_path %>

app/views/activity_types/new.html.erb
<h1>New Activity Type</h1>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>