config/routes.rb
Rails.application.routes.draw do
 # devise setup
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # home page
  root to: 'site#home'
  get 'site/home'

  resources :activities
  resources :activity_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    # add relationship that activities belong to a user
    belongs_to :user
    # add relationship that activities can only have one activity type
    has_one :activity_type
    ## validation for all fields
    validates :name, presence: true
    validates :date, presence: true
    validates :started_at, presence: true
    validates :ended_at, presence: true
    validates :activity_type_id, presence: true
    validates :user_id, presence: true
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
    has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  helper ActivitiesHelper
  # GET /activities
  # GET /activities.json
  def index
    if current_user
    @user = current_user
    @activities = @user.activities.all
    else
      redirect_to new_user_session_path, notice: 'Please log in to view activities'
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activitytype = ActivityType.find_by(id: @activity[:activity_type_id])
  end

  # GET /activities/new
  def new
    if current_user
    @activity = Activity.new
    else
      redirect_to new_user_session_path, notice: 'Please log in to record activities'
    end
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user_id = current_user.id

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully added.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.fetch(:activity, {}).permit(:name, :date, :started_at, :ended_at, :activity_type_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
# helper function for calculating activity time in hours from activity start and end times
    def duration(time_a, time_b)
        difference = time_b - time_a
        difference_hours = (difference / 3600).round(2)
        if difference_hours == 1
            return difference_hours.to_s + " hour"
        else 
            return difference_hours.to_s + " hours"
        end
    end
## helper function for checking number of activities
    def activityCount
        return @activities.count
    end
## helper function for displaying date
    def displayDate(activityDate)
        return activityDate.to_time.strftime('%b %d, %Y')
    end
## helper function for displaying time
    def displayTime(activityTime)
        return activityTime.to_time.strftime('%l:%M %p')
    end
end

app/views/activities/_form.html.erb
<div class="p-4">
<div class="form-container container p-4">
  <%= form_with(model: activity, local: true) do |form| %>

    <div class="form-group">
        <%= form.label :name, class: "font-weight-bold" %>
        <%= text_field(:activity, :name, placeholder: "E.g. Afternoon run", class: "form-control") %>
    </div>

      <div class="form-group">
          <%= form.label :activity, class: "font-weight-bold" %>
          <%= select(:activity, "activity_type_id", ActivityType.all.collect {|p| [ p.name, p.id ] }, {}, {:class => "form-control"}) %>
      </div>


    <div class="form-group">
        <%= form.label :date, class: "font-weight-bold" %>
        <%= date_field(:activity, :date, class: "form-control") %>
    </div>

    <div class="form-group">
        <%= form.label :started_at, class: "font-weight-bold" %>
        <%= time_field(:activity, :started_at, class: "form-control") %>
    </div>

    <div class="form-group">
      <%= form.label :ended_at, class: "font-weight-bold" %>
      <%= time_field(:activity, :ended_at, class: "form-control") %>
    </div>
    

    <div class="row justify-content-center">
      <%= form.submit "Save", class: "generic-button" %>
    </div>
  <% end %>
  </div>
  </div>

app/views/activities/edit.html.erb
<div class="container-fluid activity-cover p-4">
    <div class="container text-center generic-title justify-content-center">
        <h1>Edit Activity</h1>
    </div>

    <%= render 'form', activity: @activity %>

    <div class="row justify-content-center">
            <%= link_to 'Delete activity', @activity, method: :delete, data: { confirm: 'Are you sure?' }, class: "generic-button" %>
    </div>
</div>

app/views/activities/index.html.erb
<div class="activity-cover p-4">
  <div class="container text-center generic-title">
    <div class="row justify-content-center p-2">
      <h1>My Activities</h1>
    </div>
  </div>

  <% if activityCount == 0 %>
<div class="p-4">
  <div class="form-container container p-4">
    <div class="row justify-content-center text-center p-2">
      <p>Your activities will appear here</p>
    </div>
    <div class="row justify-content-center text-center">
      <p>Tap below to record your first activity</p>
    </div>
    <div class="row justify-content-center mb-3">
        <%= link_to 'New Activity →', new_activity_path, class: "generic-button" %>
      </div>
    </div>
  </div>
</div>
  
  <% else %>
<div class="p-4">
    <div class="form-container container p-4">
      <div class="row justify-content-center m-3">
      <%= link_to 'New Activity →', new_activity_path, class: "generic-button" %>
    </div>
    <div class="row">
      <% @activities.each do |activity| %>
        <div class="col-sm-6">
          <div class="card generic-card mb-3 text-center">
            <div class="card-header">
              <h5><%= activity.name %></h5>
            </div>
            <div class="card-body">
              <p><%= displayDate(activity.date) %></p>
              <p><%= ActivityType.find_by(id: activity.activity_type_id).name %></p>
              <%= link_to 'View →', activity, class: "generic-button" %>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>
</div>
</div>
<% end %>

app/views/activities/new.html.erb
<% if @activity.errors.any? %>
    <div class="alert alert-primary alert-dismissable fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= pluralize(@activity.errors.count, "error") %> prevented this activity from being saved:
        <ul>
          <% @activity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
<% end %>
<div class="container-fluid activity-cover p-4">
    <div class="container text-center generic-title">
        <div class="row justify-content-center p-2">
            <h1>New Activity</h1>
        </div>
    </div>

    <div>
        <%= render 'form', activity: @activity %>
    </div>

    <div class="row my-3 justify-content-center">
        <%= link_to '← Back to activities', activities_path, class: "generic-button-secondary" %>
    </div>
</div>

app/views/activities/show.html.erb
<div class="activity-cover p-4">
<div class="container-fluid p-3 d-flex justify-content-center">
    <div class="card generic-card border-dark">
        <div class="card-header text-center border-dark">
            <h1><%= @activity.name %></h1>
        </div>
        <div class="card-body text-center">
            <div class="card-title">
                <h2><%= @activitytype.name %></h2>
            </div>
                <p>Activity time: <%=  duration(@activity.started_at, @activity.ended_at) %><p>
                <p>Date: <%= displayDate(@activity.date) %></p>
                <p>Activity started: <%= displayTime(@activity.started_at) %></p>
                <p>Activity ended: <%= displayTime(@activity.ended_at) %></p>
            </div>
            <div class="card-footer text-center border-dark">
                <div class="row justify-content-center">
                    <div class="col-12 text-center">
                        <p>Options:<p>
                    </div>
                    <div class="col-12 m-3">
                        <%= link_to 'Edit →', edit_activity_path(@activity), class: "generic-button" %>
                    </div>
                    <div class="col-12 m-3">
                        <%= link_to '← Back', activities_path, class: "generic-button" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>